[package]
name = "http_error_derive"
version = "0.1.0"
authors = ["Hyunsik Choi <hyunsik.choi@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
